### ISSUE TITLE
Error during push request

### ISSUE THREAD

**Issue by jaredjunkin** [Sta199-S18/community#16]
Hi~

I just tried to push a portion of my lab, and it returned an error and said I was unable to do so, This is what it's telling me:

remote: Permission to Sta199-S18/lab-01-hello-r.git denied to jaredjunkin.
fatal: unable to access 'https://github.com/Sta199-S18/lab-01-hello-r.git/': The requested URL returned error: 403

Do you know how to fix this?

**Comment by mine-cetinkaya-rundel** [comment]
It appears that you are trying to push to my repository, and it won't let you since you don't have write permission there. Did you possibly skip the step of creating a repo for yourself by clicking on the assignment link? If so, it's in the announcements from last week.  You will need to:

- Click on the assignment link to create a new repo
- Create an project on RStudio.Cloud based on that repo
- Redo your edits to the lab

If you've already done a bunch of work, you could save/export that file and just copy/paste from it.

**Comment by jaredjunkin** [comment]
Hi again, 
You said I need to create my own repository to push my work. How do I do that? Sorry I'm so high maintenance! This is just really foreign to my way of thinking.

**Comment by mine-cetinkaya-rundel** [comment]
The instructions are in the Getting Started section of the lab: http://www2.stat.duke.edu/courses/Spring18/Sta199/labs/lab-01-hello-r.html.

The link for creating your repo is https://classroom.github.com/a/8ewIinG2.

It's understandable that this is all a new way of thinking, the key is to follow the instructions in the order they're outlined.

**Comment by jaredjunkin** [comment]
I've created the project in github, now I'm in Rstudio trying to paste the copied path into the gitrepo, and it's giving me this error message. Do you know where this is coming from? 

>>> git clone --progress lab-01-hello-r-jaredjunkin/lab-01-hello-r.Rmd project
fatal: repository 'lab-01-hello-r-jaredjunkin/lab-01-hello-r.Rmd' does not exist

**Comment by jaredjunkin** [comment]
My apologies, I got it!
