### ISSUE TITLE
Error Message in Rstudio Cloud

### ISSUE THREAD

**Issue by cbzaharris** [Sta199-S18/community#2]
I am trying to knit the document in Rstudio but I am getting an error message when loading my project. It says "Unhandled Exception: Child Task." I had showed Walker in our lab, but went to try again now and getting the same message. It could definitely be something on my end but not sure how to proceed. Thanks!

**Comment by mine-cetinkaya-rundel** [comment]
I peeked into your project and I'm able to reproduce the problem, which is good and bad I suppose! For this particular instance, since you didn't need to do any work in there, I would recommend

- delete your project
- fork again from my project
- open the new one

I'm hopeful the error won't persist in this new project.

However I realize that this workflow would not be good if you had work that you had done in the project as this would make you lose your work. Hence I'm looking into the error to try to find a solution. That being said, I will introduce in class tomorrow using a GitHub repository, and in lab on Thursday you'll learn how to push your work to GitHub. This will mean that you can always retrieve work that you have pushed back at any point (even if you had to restart with a fresh project).

**Comment by mine-cetinkaya-rundel** [comment]
@cbzaharris I was able to log in to your project, so I'm assuming this issue is resolved, but feel free to reopen if not.
