### ISSUE TITLE
Error: Aesthetics must be either length 1 or the same as the data (173): x, y, colour

### ISSUE THREAD

**Issue by GarrettH96** [Sta199-S18/community#24]
I am currently stuck on exercise 10 for Lab 2. When I input the following to generate a scatterplot:

```r
ggplot(data = college_recent_grads, 
            mapping = aes(x = sharewomen, y = median, color = stem_categories)) + 
  geom_point()
```

I get this error message:

```
Error: Aesthetics must be either length 1 or the same as the data (173): x, y, colour
```

Is my code incorrect, or is there another issue? I tried Googling this error but the fixes were beyond the scope of what we have learned so far.

**Comment by mine-cetinkaya-rundel** [comment]
This error is telling you that not all the variables mapped to aesthetics of the plot have the same length.

Take a look what what's in the `college_recent_grads` data frame. Do you have these three variables called `sharewomen`, `median`, and `stem_categories` in there?

My guess is that the issue is due to the `stem_categories` variable since that's the one you had to define (didn't come in the dataset originally).

**Comment by mine-cetinkaya-rundel** [comment]
Need more help on this or shall we close?

**Comment by GarrettH96** [comment]
I fixed it! Thanks for your help!
