### ISSUE TITLE
Is my work on RStudio Cloud automatically saved?

### ISSUE THREAD

**Issue by jamiepalka** [Sta199-S18/community#7]
@garylarson @mine-cetinkaya-rundel @WalkerHarrison Do I need to be somehow saving the work I do in RStudio or is it automatically saved for me? Thanks!

**Comment by mine-cetinkaya-rundel** [comment]
Your work is automatically saved in two ways:

- The cloud platform saves work
- Each time you knit your document the Rmd is saved

However, it's always good practice to 

- Save your document (click on Command/CTRL+S or the 💾 icon)
- Commit and push your changes to GitHub periodically

Never close out of your RStudio cloud session without doing these, not because your work won't otherwise get saved, but because it's better to be safe than sorry and this is good workflow that will translate to working locally (not in the cloud) later on in life.

**Comment by garylarson** [comment]
Looks like this has been solved. I'm closing the issue.
